### ISSUE TITLE
No breakpoint stepping in endless loops?

### ISSUE THREAD

**Issue by ScyDev** [okamstudio/godot#1289]
I have a while(true) loop that doesn't reach its break condition (I'm guessing) but I can't step inside it because Godot say "Process being debugged exited." before a breakpoint at the beginning of the loop is reached.

**Comment by ScyDev** [comment]
The offending line seems to be:
```
print("line index: ",indexOne," line: ",currLine)
```

I kid you not. This crashes the game and prevents the debugger from ever reaching that code block.

These variations also do it:
```
		print("test "+str(currPoly))
		print("test ",currPoly[indexOne])
		print("test ",currLine)
```

**Comment by ScyDev** [comment]
Another day another insight: 

The actual cause is that currLine is a dictionary which contains values that can reference back to currLine, thus creating a recursive reference. This crashes the game when trying to print() it.

**Comment by ScyDev** [comment]
I made a simple demo for this problem:
https://github.com/ScyDev/godot/tree/master/demos/crashes/recursive_reference_print_crash

**Comment by bojidar-bg** [comment]
Maybe we should just enforce some maximum depth when stringifying a dictionary?

**Comment by DualMatrix** [comment]
Seems to be the same issue as #8693

**Comment by Chaosus** [comment]
It seems to be, but #8693 was created far recently + the title here is better describe the problem..  instead I close #8693, and assign @reduz to this issue

**Comment by Zireael07** [comment]
Judging by #29088, it's still an issue. We could really use a warning for such situations, just to make finding them easier (I am starting to suspect I managed to fall victim to the same sort of a thing...)

**Comment by aaronfranke** [comment]
Could someone made a minimal reproduction project that works with Godot 3.2? @ScyDev The linked project in the OP is very old, it uses an `engine.cfg`. Also, maybe bump to 4.0 milestone.

**Comment by Anutrix** [comment]
It seems that this issue can be broken into separate issues of which maybe one is fixed.
Also, like aaronfranke said, it would be nice if someone could make a new MRP for 3.2 or 4.0.

**Comment by akien-mga** [comment]
The MRP from #8693 can be used in `3.x` and `master`: [hasharray.zip](https://github.com/godotengine/godot/files/6385575/hasharray.zip)

Both still crash with infinite recursion, as expected from the code:

```gdscript

extends Node

func _ready():
	var arr = []
	arr.append(arr)
	print(arr.hash())
```

**Comment by TechnoPorg** [comment]
This doesn't crash Godot for me on current `master`, using Akien's sample code. It does print the following error, though: 
```
_ready: Max recursion reached
  <C++ Source>   core\variant\array.cpp:167 @ Array::recursive_hash()
  <Stack Trace>  Node2D.gd:15 @ _ready()
```

**Comment by Calinou** [comment]
For reference, recursion checks were added in https://github.com/godotengine/godot/pull/35816 (`master`) and https://github.com/godotengine/godot/pull/42625 (`3.x).
